### ISSUE TITLE
Make `aws_iam_policy_document` optional

### ISSUE THREAD

**Issue by z0rc** [cloudposse/terraform-aws-eks-iam-role#15]
## Describe the Feature

Drop `aws_iam_policy_document` from list of required parameters.

## Expected Behavior

Module should work with `aws_iam_policy_document` argument ommited or nulled.

## Use Case

I have a case where I don't want to specify custom IAM policy for role, my plan is to attach one of managed AWS policies to role after creation.

## Describe Ideal Solution

As described in Expected behavior.

## Alternatives Considered

Passing some dummy iam policy in place seems to be working now, but it's just meh. 

## Additional Context

I need to create service account role that will be used by vpc-cni addon https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

**Comment by nitrocode** [comment]
@z0rc Try the branch `null_aws_iam_policy_document` in PR https://github.com/cloudposse/terraform-aws-eks-iam-role/pull/16 and see if it works.

**Comment by nitrocode** [comment]
You can also try just setting `aws_iam_policy_document` to `null`

**Comment by nitrocode** [comment]
This has been fixed and released as https://github.com/cloudposse/terraform-aws-eks-iam-role/releases/tag/0.9.0
