### ISSUE TITLE
service account is not created

### ISSUE THREAD

**Issue by amitca71** [cloudposse/terraform-aws-eks-iam-role#26]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
added the following code block, in order to create service account with policy:

```hcl
data "aws_caller_identity" "current" {}
#equivalent to: eksctl create iamserviceaccount --name nginx-deployment-sa --region="$REGION" --cluster "$CLUSTERNAME" --attach-policy-arn "$POLICY_ARN" --approve --override-existing-serviceaccounts
module "eks_iam_role" {
  source = "cloudposse/eks-iam-role/aws"
  service_account_name      = var.service_account_name
  service_account_namespace = var.namespace
  environment = var.environment

  aws_account_number = data.aws_caller_identity.current.account_id
  # Rather than create a whole cluster, just fake the OIDC URL
  # eks_cluster_oidc_issuer_url = module.eks_cluster.eks_cluster_identity_oidc_issuer
  eks_cluster_oidc_issuer_url = var.oidc
  aws_iam_policy_document     = [data.aws_iam_policy_document.autoallow_secrets_policy.json]

#  context = module.this.context
}
data "aws_iam_policy_document" "autoallow_secrets_policy" {
  statement {
    sid = "AllowEKSReadSecrets"
    actions = [
      "secretsmanager:GetSecretValue", "secretsmanager:DescribeSecret"
    ]
    effect    = "Allow"
    resources = [var.mysql_arn]
  }
}
data "aws_iam_policy" "secrets" {
  arn = module.eks_iam_role.service_account_policy_arn
}
```

## Expected Behavior
ServiceAccount with name secretstest@kafka would be created
 

## Steps to Reproduce
1. execute the code
2. terraform init... deploy
3. Enter '....'
service account is not created
## Screenshots

N/A

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by korenyoni** [comment]
Hi @amitca71, thank you for raising this issue.

Can you please fill out the `Environment` section in the PR description?

**Comment by rotsix** [comment]
Hey there, I'm facing the exact same issue. Here is my environment:

```
OS: archlinux 5.16.9-arch1-1
Terraform v1.1.5
EKS with Kubernetes v1.21
eks-iam-role v0.11.1
```

Please feel free to ask me if you need more informations.

**Comment by Gowiem** [comment]
@amitca71 @rotsix did either of you ever figure this out? Can we get some more information? Does Terraform fail or does it act as if it created the ServiceAccount? Do other K8s resources from your root module successfully get created in your cluster?

**Comment by Nuru** [comment]
This module is not intended to create a ServiceAccount or any Kubernetes resources. It only create the IAM role for a ServiceAccount to assume.
